### ISSUE TITLE
Plugin is undefined

### ISSUE THREAD

**Issue by dotnetdreamer** [Alone2/capacitor-notificationlistener#1]
Hello,
When i try to add the following code, then the plugin is throwing error with undefined. 
```
import { Component, OnInit } from '@angular/core';

import { SystemNotification, SystemNotificationListener } from 'capacitor-notificationlistener';

@Component({
  selector: 'app-tab1',
  templateUrl: 'tab1.page.html',
  styleUrls: ['tab1.page.scss']
})
export class Tab1Page implements OnInit {

  constructor() {}

  ngOnInit() {
    const sn = new SystemNotificationListener();
    sn.startListening();

    sn.addListener("notificationReceivedEvent", (info: SystemNotification) => {
      console.log('notificationReceivedEvent', info);
    });
    sn.addListener("notificationRemovedEvent", (info: SystemNotification) => {
      console.log('notificationRemovedEvent', info);
    });
  }
}
```
![Capture](https://user-images.githubusercontent.com/10280821/98577854-fba1de80-22d5-11eb-8dc6-fc3ec1d4af89.PNG)
Here is the console output:
```
core.js:4197 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'startListening' of undefined
TypeError: Cannot read property 'startListening' of undefined
    at SystemNotificationListener.startListening (definitions.js:16)
    at Tab1Page.ngOnInit (tab1.page.ts:16)
    at callHook (core.js:3038)
    at callHooks (core.js:3008)
    at executeInitAndCheckHooks (core.js:2960)
    at refreshView (core.js:7187)
    at renderComponentOrTemplate (core.js:7286)
    at tickRootContext (core.js:8498)
    at detectChangesInRootView (core.js:8523)
    at RootViewRef.detectChanges (core.js:9899)
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:27425)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)

```

**Comment by Alone2** [comment]
Thank you for opening this issue. I'll look into it as soon as i can :D

**Comment by Alone2** [comment]
I tried to replicate your issue but did not succeed. 

Keep in mind that this plugin only works on android and not on iOS or the web. 
Install this plugin using 'npm i capacitor-notificationlistener' and 'npx cap sync'
If you have problems or errors in android studio [this link](https://capacitorjs.com/docs/android/troubleshooting) can help.
Also check if capacitor is correctly installed. 

[Here](https://github.com/Alone2/test-angular) is my replica of your code that works on my machine.

I hope I was able to help you. I'm not a JavaScript or Typescript expert so I'm not sure if I can help you any further.

However, please contact me if you still encounter this problem, I'll try my hardest to solve it! :smile:

**Comment by dotnetdreamer** [comment]
i created a pull request. Actually i was missing the registration of plugin in MainActivity... Thanks!
